repos:
    - repo: https://github.com/ambv/black
      rev: 19.3b0
      hooks:
          - id: black
            language_version: python3
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.720
      hooks:
          - id: mypy
            exclude: tests/data/*
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
          - id: flake8
            exclude: ^build/*
            additional_dependencies:
                - flake8-builtins
                - flake8-comprehensions
                - flake8-docstrings
                - flake8-tuple
                - flake8-quotes
                - pep8-naming
                - pydocstyle<4.0.0
